//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RID.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class objeto_por_salida
    {
        public int id_objeto_por_salida { get; set; }
        public int id_salida { get; set; }
        public int id_objeto { get; set; }
    
        public virtual salida salida { get; set; }
    }
}
